CREATE TABLE TASKS(
	ID int IDENTITY(1,1) PRIMARY KEY,
	NAME nvarchar(2000) NOT NULL,
	DATE datetime NOT NULL,
	STARTTIME nvarchar(10) NOT NULL,
	ENDTIME nvarchar(10) NOT NULL,
	USERID int FOREIGN KEY REFERENCES EMPLOYEE(ID)
);



